### ISSUE TITLE
"Station_wagon" is een invalid enumeration member (const.py)

### ISSUE THREAD

**Issue by Calimerorulez** [frenck/python-vehicle#27]
Kleine bug m.b.t. de dataset bij Inrichting:

```
Traceback (most recent call last):
  File "/home/docker/scripts/rdw.py", line 39, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/docker/scripts/rdw.py", line 11, in main
    vehicle: Vehicle = await rdw.vehicle(license_plate="NS966G")
  File "/home/docker/.local/lib/python3.9/site-packages/vehicle/rdw.py", line 135, in vehicle
    return Vehicle.parse_obj(data[0])  # type: ignore
  File "pydantic/main.py", line 578, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 406, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Vehicle
inrichting
  value is not a valid enumeration member; permitted: 'kampeerwagen', 'caravan', 'closed_interior', 'cabriolet', 'coupe', 'brandweerwagen', 'hatchback', 'veewagen', 'MPV', 'open laadvloer', 'open wagen', 'sedan', 'station_wagon' (type=type_error.enum; enum_values=[<VehicleInterior.CAMPER: 'kampeerwagen'>, <VehicleInterior.CARAVAN: 'caravan'>, <VehicleInterior.CLOSED_INTERIOR: 'closed_interior'>, <VehicleInterior.CONVERTIBLE: 'cabriolet'>, <VehicleInterior.COUPE: 'coupe'>, <VehicleInterior.FIRETRUCK: 'brandweerwagen'>, <VehicleInterior.HATCHBACK: 'hatchback'>, <VehicleInterior.LIVESTOCK_TRUCK: 'veewagen'>, <VehicleInterior.MPV: 'MPV'>, <VehicleInterior.OPEN_LOADING_FLOOR: 'open laadvloer'>, <VehicleInterior.OPEN_VEHICLE: 'open wagen'>, <VehicleInterior.SEDAN: 'sedan'>, <VehicleInterior.STATION_WAGON: 'station_wagon'>])
```

Volgens de RDW dataset is het 'stationwagen' i.p.v. 'station_wagon'.

Ik heb een PR geopend (#28), mijn eerste ooit, dus ik weet niet of ik het goed doe ;)

**Comment by frenck** [comment]
Thanks, @Calimerorulez ❤️ 

Released version 0.2.1 with the contributed fix
